# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-03 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('num_params', models.PositiveSmallIntegerField()),
                ('signature', models.CharField(blank=True, max_length=256)),
                ('description', models.CharField(default='', max_length=1000)),
                ('content', models.TextField(default='', max_length=64000)),
            ],
            options={
                'ordering': ['signature'],
            },
        ),
    ]
